name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          spm-package: ./
          scheme: FloatingTabView
          destination: platform=iOS Simulator,OS=15.0,name=iPhone 13 Pro
          action: build
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          spm-package: ./
          scheme: FloatingTabView
          destination: platform=iOS Simulator,OS=15.0,name=iPhone 13 Pro
          action: test